### ISSUE TITLE
Set extraData just before upload

### ISSUE THREAD

**Issue by neuront** [danielm/uploader#11]
hi, thanks for your work.

Is it possible to set `extraData` just before upload? Like this

``` js
$('#dmuploader-div').dmUploader({
    onBeforeUpload: function() {
        $(this).extraData = {someField: $('#some-input').val()};    
    }
})
```

**Comment by dellert** [comment]
this doen't work on multiple/ first file upload, but for second javascript tells: use *settings* of undefined

**Comment by autorunman22** [comment]
> Thanks for tying the plugin!
> 
> Yeah, its an issue that also other people are having as well.
> 
> First use the dmuploader.js / dmuploader.min.js from the Git repo, i just commited a small tweak to the code; and then use something like this:
> 
> ```js
> onBeforeUpload: function() {
>     $('#drag-and-drop-zone').data('dmUploader').settings.extraData = {
>         someField: $('#some-input').val()
>     };
> }
> ```
> 
> Not a big fan of this, but it will get the job done until the new version is released with a proper solution for these kind of issues.
> 
> Cheers!

Found the fix for this. Right after the setup, store the instance to a variable for later use. 
On the next upload, direct access the `extraData` provided from the `settings`
` dnd.data('dmUploader').settings.extraData = extraData`

That should dynamically add any extra payloads on your subsequent requests!
