### ISSUE TITLE
is there are any way to limit number of uploaded files with multy true?

### ISSUE THREAD

**Issue by Prospection** [danielm/uploader#113]
subj

**Comment by cheema14** [comment]
Looking for the same solution. I am stuck

**Comment by danielm** [comment]
Hey,

in the past was kinda an option..... but seems like everyone wanted a different behavior out of it. (like based on uploads completed, or maybe selected files, or even server response).
This was actually removed because it was a mess and made no sense to keep it during last update, for this kind of feature u may went to use onnewfile / uploadcompleted callbacks and build it according for your own requirements.
