### ISSUE TITLE
extraData dont change on fly

### ISSUE THREAD

**Issue by laurisnets** [danielm/uploader#19]
I found that parameter "extraData" dont update itself.
(extraData takes only first value, if I change value in select box it does not update)

For example:

$("#drag-and-drop-zone").dmUploader({
        url: '/admins/modules/gallery/new_image.php?gallery='+gallery_id,
        dataType: 'json',
        fileName: 'files', 
        allowedTypes: 'image/*',
        extFilter: 'jpg;png;gif', 
        extraData: {
            gallery: $('#gallery_id option:seletced').val()
        },
..........

**Comment by debasispanda** [comment]
I am facing the same issue. Unable to pass extra data dynamically on form field change. 

How to resolve this issue ?

**Comment by debasispanda** [comment]
Hi I found one way to resolve this issue. Please find below.

// Change the extraData to a function instead of static object. 
extraData: function(){
  var data = {}, g = $('#gallery_id option:seletced').val();
  if(g){
     data.gallery = g;
     return data;
  }
  else{
    console.error('Select the gallery id');
    return false;
  }  
},


In addition to that you should call the "extraData" function each time you drop a file and add the data to the file data.

I preferred to do this in "a.prototype.processQueue()" as follows. Add the following section.

var d;
if(typeof(h.settings.extraData) === "function"){
            d = h.settings.extraData();
        }
        else{
            d = h.settings.extraData;
        }

        c.each(d, function(i, j) {
            f.append(i, j)
});

**Comment by danielm** [comment]
Closing the issue. For future reference, included in newest release.

**Comment by autorunman22** [comment]
> Closing the issue. For future reference, included in newest release.

Still having this issue
