### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by devries123** [danielm/uploader#3]
Hello,

I'm trying to use your uploader, but I have a problem. I get it to show and work as long as I don't put anything more in the upload.php . Once I put my php code for uploading in it, it gives the following error:

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

I use the following code to upload the (multiple) files to the server:

$dir = 'test/';
    if(is_uploaded_file($_FILES['files']['tmp_name'])){
        $file = $_FILES['files']['name'];
            if(move_uploaded_file($_FILES['files']['tmp_name'], $dir.$file))
            {
                echo json_encode(array('status' => 'ok'));
            }
            else
            {
            }
    }

Do you know how to fix this error?

**Comment by zevero** [comment]
Just tried it with nodejs and got a "Syntax Error", when returning just a string "ok".

The reason is, that I copied your example. And it uses
`JSON.stringify(data)`
which naturally throws an errror.

Returning a json object like
` {status:"ok"}`
or
`{status:"error", msg:"Error message"}`
helped ...
Maybe you should state the server side requirements in the readme.

I know now... there are no requirements. It depends entirely on jquery...
... but if I had known this, I would have felt easier :)

Very nice plugin! Thank you very much to share it with us!
